spring:
  main:
    banner-mode: off
  application:
    name: spring-boot-freemarker-integration
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  sql:
    init:
      platform: h2

server:
  port: 8080
